import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    position: "absolute",
    width: 428,
    height: 576,
    left: 0,
    top: 0,
  },
  sun: {
    position: "absolute",
    width: 371,
    height: 371,
    left: 9,
    top: 277,
  },
  welcome: {
    position: "absolute",
    width: 356,
    height: 606,
    left: 20,
    top: 75,
    // fontFamily: "Raleway",
    // fontStyle: "normal",
    // fontWeight: 600,
    fontSize: 70,
    lineHeight: 82,
    textAlign: "center",
    color: "#5C5C5C",
  },
  rightHill: {
    position: "absolute",
    width: 917.46,
    height: 633.46,
    left: -245,
    top: 434,
  },
  leftHill: {
    position: "absolute",
    width: 545.47,
    height: 388.14,
    left: -167.5,
    top: 400,
  },
  rockFlag: {
    position: "absolute",
    width: 633,
    height: 732.21,
    left: -138,
    top: 373,
  },
  btn: {
    position: "absolute",
    width: 235.02,
    height: 63.23,
    left: 89.96,
    top: 700,
    backgroundColor: "#FFFFFF",
    borderRadius: 16.7018,
  },
  btnText: {
    // position: "absolute",
    // width: 240.98,
    // height: 68,
    // left: 94,
    // top: 732,
    /* Let’s get started */

    color: "#5c5c5c",
    position: "absolute",
    width: 207.58,
    height: 27.44,
    left: 15,
    top: 15,
    justifyContent: "center",
    alignItems: "center",
    // fontFamily: "Raleway",
    // fontStyle: "normal",
    // fontWeight: 600,
    fontSize: 24,
    lineHeight: 28,
    textAlign: "center",
  },
  scrollingRock: {
    position: "absolute",
    width: 464.5,
    height: 1014.5,
    left: -36.5,
    top: 197.5,
  },
  fadingContainer: {
    // padding: ,
    // backgroundColor: "powderblue",
  },
});
export default styles;
